
##    softmax 以及损失计算
    
##### 1.本文主要讲述 ：CrossEntropyLoss() 和 NLLLoss() 的区别以及他们和Softmax的关系


In [4]:
# 本文头文件导入
import torch
import torch.nn as nn

In [2]:
#  输出矩阵，假设输入3张图片，分3类，最后的输出是一个3*3的tensor
#  第1，2，3行分别是 第1，2，3张图片的结果，第1，2，3列分别是3个分类的得分，如1，2，3列，分别是猫、狗和猪的分类得分

input = torch.randn(3,3) # 随机产生一个3*3的矩阵，tensor类型
input


input = torch.tensor([[-0.1342,-2.5835,-0.9810],
                     [0.1867,-1.4513,-0.3225],
                      [0.6272,-0.1120,0.3048]          
                     ])
input

tensor([[-0.1342, -2.5835, -0.9810],
        [ 0.1867, -1.4513, -0.3225],
        [ 0.6272, -0.1120,  0.3048]])

In [5]:
# 对每一行使用softmax，可得到每张图片的概率分布
sm = nn.Softmax(dim=1)
sm(input)

# dim = 1 表示按行计算softmax
# dim = 0 表示按列计算softmax
# 结果解释，可以看出3张图片，最有可能的标签分别是，猪，狗，猪

tensor([[0.6600, 0.0570, 0.2830],
        [0.5570, 0.1083, 0.3347],
        [0.4542, 0.2169, 0.3290]])

In [6]:
input = torch.log(sm(input)) 
input
# 对每个分数 求 ln()，因为每个分数的概率本来是小于1大于0的。所以求ln后都变成了(0,-无穷)的值了

tensor([[-0.4155, -2.8648, -1.2623],
        [-0.5852, -2.2232, -1.0944],
        [-0.7893, -1.5285, -1.1117]])

In [7]:
# NLLLoss的结果就是把上面的输出  与  Label对应的那个值拿出来，再去掉负号，再求均值。

# 0猫、1狗 和2猪，表示标签的值
# 假设我们现在的target是【0,2,1】（第一张图片是猫，第二张图片是猪，第三章是狗），第一行取第0列元素，第二行取第2列元素，第三行取第1列
# 现在 取 [0.6703,1.2447,0.9952]

(0.4155+1.0945+1.5285) / 3

# 参考之前设定的 如1，2，3列，分别是猫、狗和猪的分类得分

1.0128333333333333

In [8]:
# 验证NLLLoss

loss = nn.NLLLoss()
target = torch.tensor([0,2,1])
loss(input,target)  # input = torch.randn(3,3)

tensor(1.0128)

In [9]:
input = torch.tensor([[-0.1342,-2.5835,-0.9810],
                     [0.1867,-1.4513,-0.3225],
                      [0.6272,-0.1120,0.3048]          
                     ])

# crossEntropyLoss 等于  softmax-->max -->NLLLoss,将这几个过程合并起来了。
loss = nn.CrossEntropyLoss()
target = torch.tensor([0,2,1])
loss(input,target)

tensor(1.0128)